version: '3.7'

services:
  backend:
    build: ./
    container_name: backend
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - zookeeper
    
  zookeeper:
    container_name: zookeeper 
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/data

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
    # command:  /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic test-topic
  
  clickhouse:
    container_name: clickhouse
    image: 'clickhouse/clickhouse-server'
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    env_file:
      - .env
    environment:
      - CLICKHOUSE_USER=${CH_USERNAME}
      - CLICKHOUSE_DATABASE=${CH_NAME}
      - CLICKHOUSE_PASSWORD=${CH_PASSWORD}
volumes:
  zookeeper_data:
  clickhouse_data: